<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
/**
* Run the database seeds.
*
* @return void
*/
public function run()
{
	DB::table('countries')->delete();
	$countries = array(
		array('id' => 1,'code' => 'AF' ,'name_en' => "Afghanistan", 'name_ar' => "أفغانستان", 'phonecode' => 93),
		array('id' => 2,'code' => 'AL' ,'name_en' => "Albania", 'name_ar' => "ألبانيا", 'phonecode' => 355),
		array('id' => 3,'code' => 'DZ' ,'name_en' => "Algeria", 'name_ar' => "الجزائر", 'phonecode' => 213),
		array('id' => 4,'code' => 'AS' ,'name_en' => "American Samoa", 'name_ar' => "ساموا الأمريكية", 'phonecode' => 1684),
		array('id' => 5,'code' => 'AD' ,'name_en' => "Andorra", 'name_ar' => "أندورا", 'phonecode' => 376),
		array('id' => 6,'code' => 'AO' ,'name_en' => "Angola", 'name_ar' => "أنغولا", 'phonecode' => 244),
		array('id' => 7,'code' => 'AI' ,'name_en' => "Anguilla", 'name_ar' => "أنغويلا", 'phonecode' => 1264),
		array('id' => 8,'code' => 'AQ' ,'name_en' => "Antarctica", 'name_ar' => "أنتاركتيكا", 'phonecode' => 0),
		array('id' => 9,'code' => 'AG' ,'name_en' => "Antigua And Barbuda", 'name_ar' => "أنتيغوا وبربودا", 'phonecode' => 1268),
		array('id' => 10,'code' => 'AR','name_en' => "Argentina", 'name_ar' => "الأرجنتين", 'phonecode' => 54),
		array('id' => 11,'code' => 'AM','name_en' => "Armenia", 'name_ar' => "أرمينيا", 'phonecode' => 374),
		array('id' => 12,'code' => 'AW','name_en' => "Aruba", 'name_ar' => "أروبا", 'phonecode' => 297),
		array('id' => 13,'code' => 'AU','name_en' => "Australia", 'name_ar' => "أستراليا", 'phonecode' => 61),
		array('id' => 14,'code' => 'AT','name_en' => "Austria", 'name_ar' => "النمسا", 'phonecode' => 43),
		array('id' => 15,'code' => 'AZ','name_en' => "Azerbaijan", 'name_ar' => "أذربيجان", 'phonecode' => 994),
		array('id' => 16,'code' => 'BS','name_en' => "Bahamas The", 'name_ar' => "جزر البهاما", 'phonecode' => 1242),
		array('id' => 17,'code' => 'BH','name_en' => "Bahrain", 'name_ar' => "البحرين", 'phonecode' => 973),
		array('id' => 18,'code' => 'BD','name_en' => "Bangladesh", 'name_ar' => "بنغلاديش", 'phonecode' => 880),
		array('id' => 19,'code' => 'BB','name_en' => "Barbados", 'name_ar' => "بربادوس", 'phonecode' => 1246),
		array('id' => 20,'code' => 'BY','name_en' => "Belarus", 'name_ar' => "بيلاروسيا", 'phonecode' => 375),
		array('id' => 21,'code' => 'BE','name_en' => "Belgium", 'name_ar' => "بلجيكا", 'phonecode' => 32),
		array('id' => 22,'code' => 'BZ','name_en' => "Belize", 'name_ar' => "بليز", 'phonecode' => 501),
		array('id' => 23,'code' => 'BJ','name_en' => "Benin", 'name_ar' => "بنين", 'phonecode' => 229),
		array('id' => 24,'code' => 'BM','name_en' => "Bermuda", 'name_ar' => "برمودا", 'phonecode' => 1441),
		array('id' => 25,'code' => 'BT','name_en' => "Bhutan", 'name_ar' => "بوتان", 'phonecode' => 975),
		array('id' => 26,'code' => 'BO','name_en' => "Bolivia", 'name_ar' => "بوليفيا", 'phonecode' => 591),
		array('id' => 27,'code' => 'BA','name_en' => "Bosnia and Herzegovina", 'name_ar' => "البوسنة والهرسك", 'phonecode' => 387),
		array('id' => 28,'code' => 'BW','name_en' => "Botswana", 'name_ar' => "بوتسوانا", 'phonecode' => 267),
		array('id' => 29,'code' => 'BV','name_en' => "Bouvet Island", 'name_ar' => "جزيرة بوفيت", 'phonecode' => 0),
		array('id' => 30,'code' => 'BR','name_en' => "Brazil", 'name_ar' => "البرازيل", 'phonecode' => 55),
		array('id' => 31,'code' => 'IO','name_en' => "British Indian Ocean Territory", 'name_ar' => "إقليم المحيط البريطاني الهندي", 'phonecode' => 246),
		array('id' => 32,'code' => 'BN','name_en' => "Brunei", 'name_ar' => "بروناي", 'phonecode' => 673),
		array('id' => 33,'code' => 'BG','name_en' => "Bulgaria", 'name_ar' => "بلغاريا", 'phonecode' => 359),
		array('id' => 34,'code' => 'BF','name_en' => "Burkina Faso", 'name_ar' => "بوركينا فاسو", 'phonecode' => 226),
		array('id' => 35,'code' => 'BI','name_en' => "Burundi", 'name_ar' => "بوروندي", 'phonecode' => 257),
		array('id' => 36,'code' => 'KH','name_en' => "Cambodia", 'name_ar' => "كمبوديا", 'phonecode' => 855),
		array('id' => 37,'code' => 'CM','name_en' => "Cameroon", 'name_ar' => "الكاميرون", 'phonecode' => 237),
		array('id' => 38,'code' => 'CA','name_en' => "Canada", 'name_ar' => "كندا", 'phonecode' => 1),
		array('id' => 39,'code' => 'CV','name_en' => "Cape Verde", 'name_ar' => "الرأس الأخضر", 'phonecode' => 238),
		array('id' => 40,'code' => 'KY','name_en' => "Cayman Islands", 'name_ar' => "جزر كايمان", 'phonecode' => 1345),
		array('id' => 41,'code' => 'CF','name_en' => "Central African Republic", 'name_ar' => "جمهورية افريقيا الوسطى", 'phonecode' => 236),
		array('id' => 42,'code' => 'TD','name_en' => "Chad", 'name_ar' => "تشاد", 'phonecode' => 235),
		array('id' => 43,'code' => 'CL','name_en' => "Chile", 'name_ar' => "تشيلي", 'phonecode' => 56),
		array('id' => 44,'code' => 'CN','name_en' => "China", 'name_ar' => "الصين", 'phonecode' => 86),
		array('id' => 45,'code' => 'CX','name_en' => "Christmas Island", 'name_ar' => "جزيرة الكريسماس", 'phonecode' => 61),
		array('id' => 46,'code' => 'CC','name_en' => "Cocos (Keeling) Islands", 'name_ar' => "جزر كوكوس (كيلينغ)", 'phonecode' => 672),
		array('id' => 47,'code' => 'CO','name_en' => "Colombia", 'name_ar' => "كولومبيا", 'phonecode' => 57),
		array('id' => 48,'code' => 'KM','name_en' => "Comoros", 'name_ar' => "جزر القمر", 'phonecode' => 269),
		array('id' => 49,'code' => 'CG','name_en' => "Congo", 'name_ar' => "الكونغو", 'phonecode' => 242),
		array('id' => 50,'code' => 'CD','name_en' => "Congo The Democratic Republic Of The", 'name_ar' => "جمهورية الكونغو الديمقراطية", 'phonecode' => 242),
		array('id' => 51,'code' => 'CK','name_en' => "Cook Islands", 'name_ar' => "جزر كوك", 'phonecode' => 682),
		array('id' => 52,'code' => 'CR','name_en' => "Costa Rica", 'name_ar' => "كوستا ريكا", 'phonecode' => 506),
		array('id' => 53,'code' => 'CI','name_en' => "Cote D Ivoire (Ivory Coast)", 'name_ar' => "ساحل العاج، كوت ديفوار", 'phonecode' => 225),
		array('id' => 54,'code' => 'HR','name_en' => "Croatia (Hrvatska)", 'name_ar' => "كرواتيا (هرفاتسكا)", 'phonecode' => 385),
		array('id' => 55,'code' => 'CU','name_en' => "Cuba", 'name_ar' => "كوبا", 'phonecode' => 53),
		array('id' => 56,'code' => 'CY','name_en' => "Cyprus", 'name_ar' => "قبرص", 'phonecode' => 357),
		array('id' => 57,'code' => 'CZ','name_en' => "Czech Republic", 'name_ar' => "الجمهورية التشيكية", 'phonecode' => 420),
		array('id' => 58,'code' => 'DK','name_en' => "Denmark", 'name_ar' => "الدنمارك", 'phonecode' => 45),
		array('id' => 59,'code' => 'DJ','name_en' => "Djibouti", 'name_ar' => "جيبوتي", 'phonecode' => 253),
		array('id' => 60,'code' => 'DM','name_en' => "Dominica", 'name_ar' => "دومينيكا", 'phonecode' => 1767),
		array('id' => 61,'code' => 'DO','name_en' => "Dominican Republic", 'name_ar' => "جمهورية الدومينيكان", 'phonecode' => 1809),
		array('id' => 62,'code' => 'TP','name_en' => "East Timor", 'name_ar' => "تيمور الشرقية", 'phonecode' => 670),
		array('id' => 63,'code' => 'EC','name_en' => "Ecuador", 'name_ar' => "الاكوادور", 'phonecode' => 593),
		array('id' => 64,'code' => 'EG','name_en' => "Egypt", 'name_ar' => "مصر", 'phonecode' => 20),
		array('id' => 65,'code' => 'SV','name_en' => "El Salvador", 'name_ar' => "السلفادور", 'phonecode' => 503),
		array('id' => 66,'code' => 'GQ','name_en' => "Equatorial Guinea", 'name_ar' => "غينيا الإستوائية", 'phonecode' => 240),
		array('id' => 67,'code' => 'ER','name_en' => "Eritrea", 'name_ar' => "إريتريا", 'phonecode' => 291),
		array('id' => 68,'code' => 'EE','name_en' => "Estonia", 'name_ar' => "إستونيا", 'phonecode' => 372),
		array('id' => 69,'code' => 'ET','name_en' => "Ethiopia", 'name_ar' => "أثيوبيا", 'phonecode' => 251),
		array('id' => 70,'code' => 'XA','name_en' => "External Territories of Australia", 'name_ar' => "الأقاليم الخارجية لأستراليا", 'phonecode' => 61),
		array('id' => 71,'code' => 'FK','name_en' => "Falkland Islands", 'name_ar' => "جزر فوكلاند", 'phonecode' => 500),
		array('id' => 72,'code' => 'FO','name_en' => "Faroe Islands", 'name_ar' => "جزر فاروس", 'phonecode' => 298),
		array('id' => 73,'code' => 'FJ','name_en' => "Fiji Islands", 'name_ar' => "جزر فيجي", 'phonecode' => 679),
		array('id' => 74,'code' => 'FI','name_en' => "Finland", 'name_ar' => "فنلندا", 'phonecode' => 358),
		array('id' => 75,'code' => 'FR','name_en' => "France", 'name_ar' => "فرنسا", 'phonecode' => 33),
		array('id' => 76,'code' => 'GF','name_en' => "French Guiana", 'name_ar' => "غيانا الفرنسية", 'phonecode' => 594),
		array('id' => 77,'code' => 'PF','name_en' => "French Polynesia", 'name_ar' => "بولينيزيا الفرنسية", 'phonecode' => 689),
		array('id' => 78,'code' => 'TF','name_en' => "French Southern Territories", 'name_ar' => "المناطق الجنوبية لفرنسا", 'phonecode' => 0),
		array('id' => 79,'code' => 'GA','name_en' => "Gabon", 'name_ar' => "الجابون", 'phonecode' => 241),
		array('id' => 80,'code' => 'GM','name_en' => "Gambia The", 'name_ar' => "غامبيا", 'phonecode' => 220),
		array('id' => 81,'code' => 'GE','name_en' => "Georgia", 'name_ar' => "جورجيا", 'phonecode' => 995),
		array('id' => 82,'code' => 'DE','name_en' => "Germany", 'name_ar' => "ألمانيا", 'phonecode' => 49),
		array('id' => 83,'code' => 'GH','name_en' => "Ghana", 'name_ar' => "غانا", 'phonecode' => 233),
		array('id' => 84,'code' => 'GI','name_en' => "Gibraltar", 'name_ar' => "جبل طارق", 'phonecode' => 350),
		array('id' => 85,'code' => 'GR','name_en' => "Greece", 'name_ar' => "اليونان", 'phonecode' => 30),
		array('id' => 86,'code' => 'GL','name_en' => "Greenland", 'name_ar' => "الأرض الخضراء", 'phonecode' => 299),
		array('id' => 87,'code' => 'GD','name_en' => "Grenada", 'name_ar' => "غرينادا", 'phonecode' => 1473),
		array('id' => 88,'code' => 'GP','name_en' => "Guadeloupe", 'name_ar' => "جوادلوب", 'phonecode' => 590),
		array('id' => 89,'code' => 'GU','name_en' => "Guam", 'name_ar' => "غوام", 'phonecode' => 1671),
		array('id' => 90,'code' => 'GT','name_en' => "Guatemala", 'name_ar' => "غواتيمالا", 'phonecode' => 502),
		array('id' => 91,'code' => 'XU','name_en' => "Guernsey and Alderney", 'name_ar' => "غيرنزي وألدرني", 'phonecode' => 44),
		array('id' => 92,'code' => 'GN','name_en' => "Guinea", 'name_ar' => "غينيا", 'phonecode' => 224),
		array('id' => 93,'code' => 'GW','name_en' => "Guinea-Bissau", 'name_ar' => "غينيا بيساو", 'phonecode' => 245),
		array('id' => 94,'code' => 'GY','name_en' => "Guyana", 'name_ar' => "غيانا", 'phonecode' => 592),
		array('id' => 95,'code' => 'HT','name_en' => "Haiti", 'name_ar' => "هايتي", 'phonecode' => 509),
		array('id' => 96,'code' => 'HM','name_en' => "Heard and McDonald Islands", 'name_ar' => "جزر هيرد وماكدونالد", 'phonecode' => 0),
		array('id' => 97,'code' => 'HN','name_en' => "Honduras", 'name_ar' => "هندوراس", 'phonecode' => 504),
		array('id' => 98,'code' => 'HK','name_en' => "Hong Kong S.A.R.", 'name_ar' => "منطقة هونغ كونغ الإدارية الخاصة", 'phonecode' => 852),
		array('id' => 99,'code' => 'HU','name_en' => "Hungary", 'name_ar' => "هنغاريا", 'phonecode' => 36),
		array('id' => 100,'code' => 'IS','name_en' => "Iceland", 'name_ar' => "أيسلندا", 'phonecode' => 354),
		array('id' => 101,'code' => 'IN','name_en' => "India", 'name_ar' => "الهند", 'phonecode' => 91),
		array('id' => 102,'code' => 'ID','name_en' => "Indonesia", 'name_ar' => "إندونيسيا", 'phonecode' => 62),
		array('id' => 103,'code' => 'IR','name_en' => "Iran", 'name_ar' => "إيران", 'phonecode' => 98),
		array('id' => 104,'code' => 'IQ','name_en' => "Iraq", 'name_ar' => "العراق", 'phonecode' => 964),
		array('id' => 105,'code' => 'IE','name_en' => "Ireland", 'name_ar' => "أيرلندا", 'phonecode' => 353),
		array('id' => 106,'code' => 'IL','name_en' => "Israel", 'name_ar' => "إسرائيل", 'phonecode' => 972),
		array('id' => 107,'code' => 'IT','name_en' => "Italy", 'name_ar' => "إيطاليا", 'phonecode' => 39),
		array('id' => 108,'code' => 'JM','name_en' => "Jamaica", 'name_ar' => "جامايكا", 'phonecode' => 1876),
		array('id' => 109,'code' => 'JP','name_en' => "Japan", 'name_ar' => "اليابان", 'phonecode' => 81),
		array('id' => 110,'code' => 'XJ','name_en' => "Jersey", 'name_ar' => "جيرسي", 'phonecode' => 44),
		array('id' => 111,'code' => 'JO','name_en' => "Jordan", 'name_ar' => "الأردن", 'phonecode' => 962),
		array('id' => 112,'code' => 'KZ','name_en' => "Kazakhstan", 'name_ar' => "كازاخستان", 'phonecode' => 7),
		array('id' => 113,'code' => 'KE','name_en' => "Kenya", 'name_ar' => "كينيا", 'phonecode' => 254),
		array('id' => 114,'code' => 'KI','name_en' => "Kiribati", 'name_ar' => "كيريباتي", 'phonecode' => 686),
		array('id' => 115,'code' => 'KP','name_en' => "Korea North", 'name_ar' => "كوريا الشمالية", 'phonecode' => 850),
		array('id' => 116,'code' => 'KR','name_en' => "Korea South", 'name_ar' => "كوريا الجنوبية", 'phonecode' => 82),
		array('id' => 117,'code' => 'KW','name_en' => "Kuwait", 'name_ar' => "الكويت", 'phonecode' => 965),
		array('id' => 118,'code' => 'KG','name_en' => "Kyrgyzstan", 'name_ar' => "قيرغيزستان", 'phonecode' => 996),
		array('id' => 119,'code' => 'LA','name_en' => "Laos", 'name_ar' => "لاوس", 'phonecode' => 856),
		array('id' => 120,'code' => 'LV','name_en' => "Latvia", 'name_ar' => "لاتفيا", 'phonecode' => 371),
		array('id' => 121,'code' => 'LB','name_en' => "Lebanon", 'name_ar' => "لبنان", 'phonecode' => 961),
		array('id' => 122,'code' => 'LS','name_en' => "Lesotho", 'name_ar' => "ليسوتو", 'phonecode' => 266),
		array('id' => 123,'code' => 'LR','name_en' => "Liberia", 'name_ar' => "ليبيريا", 'phonecode' => 231),
		array('id' => 124,'code' => 'LY','name_en' => "Libya", 'name_ar' => "ليبيا", 'phonecode' => 218),
		array('id' => 125,'code' => 'LI','name_en' => "Liechtenstein", 'name_ar' => "ليختنشتاين", 'phonecode' => 423),
		array('id' => 126,'code' => 'LT','name_en' => "Lithuania", 'name_ar' => "ليتوانيا", 'phonecode' => 370),
		array('id' => 127,'code' => 'LU','name_en' => "Luxembourg", 'name_ar' => "لوكسمبورغ", 'phonecode' => 352),
		array('id' => 128,'code' => 'MO','name_en' => "Macau S.A.R.", 'name_ar' => "ماكاو الإدارية الخاصة", 'phonecode' => 853),
		array('id' => 129,'code' => 'MK','name_en' => "Macedonia", 'name_ar' => "مقدونيا", 'phonecode' => 389),
		array('id' => 130,'code' => 'MG','name_en' => "Madagascar", 'name_ar' => "مدغشقر", 'phonecode' => 261),
		array('id' => 131,'code' => 'MW','name_en' => "Malawi", 'name_ar' => "ملاوي", 'phonecode' => 265),
		array('id' => 132,'code' => 'MY','name_en' => "Malaysia", 'name_ar' => "ماليزيا", 'phonecode' => 60),
		array('id' => 133,'code' => 'MV','name_en' => "Maldives", 'name_ar' => "جزر المالديف", 'phonecode' => 960),
		array('id' => 134,'code' => 'ML','name_en' => "Mali", 'name_ar' => "مالي", 'phonecode' => 223),
		array('id' => 135,'code' => 'MT','name_en' => "Malta", 'name_ar' => "مالطا", 'phonecode' => 356),
		array('id' => 136,'code' => 'XM','name_en' => "Man (Isle of)", 'name_ar' => "جزيرة مان", 'phonecode' => 44),
		array('id' => 137,'code' => 'MH','name_en' => "Marshall Islands", 'name_ar' => "جزر مارشال", 'phonecode' => 692),
		array('id' => 138,'code' => 'MQ','name_en' => "Martinique", 'name_ar' => "مارتينيك", 'phonecode' => 596),
		array('id' => 139,'code' => 'MR','name_en' => "Mauritania", 'name_ar' => "موريتانيا", 'phonecode' => 222),
		array('id' => 140,'code' => 'MU','name_en' => "Mauritius", 'name_ar' => "موريشيوس", 'phonecode' => 230),
		array('id' => 141,'code' => 'YT','name_en' => "Mayotte", 'name_ar' => "مايوت", 'phonecode' => 269),
		array('id' => 142,'code' => 'MX','name_en' => "Mexico", 'name_ar' => "المكسيك", 'phonecode' => 52),
		array('id' => 143,'code' => 'FM','name_en' => "Micronesia", 'name_ar' => "ميكرونيزيا", 'phonecode' => 691),
		array('id' => 144,'code' => 'MD','name_en' => "Moldova", 'name_ar' => "مولدوفا", 'phonecode' => 373),
		array('id' => 145,'code' => 'MC','name_en' => "Monaco", 'name_ar' => "موناكو", 'phonecode' => 377),
		array('id' => 146,'code' => 'MN','name_en' => "Mongolia", 'name_ar' => "منغوليا", 'phonecode' => 976),
		array('id' => 147,'code' => 'MS','name_en' => "Montserrat", 'name_ar' => "مونتسيرات", 'phonecode' => 1664),
		array('id' => 148,'code' => 'MA','name_en' => "Morocco", 'name_ar' => "المغرب", 'phonecode' => 212),
		array('id' => 149,'code' => 'MZ','name_en' => "Mozambique", 'name_ar' => "موزمبيق", 'phonecode' => 258),
		array('id' => 150,'code' => 'MM','name_en' => "Myanmar", 'name_ar' => "ميانمار", 'phonecode' => 95),
		array('id' => 151,'code' => 'NA','name_en' => "Namibia", 'name_ar' => "ناميبيا", 'phonecode' => 264),
		array('id' => 152,'code' => 'NR','name_en' => "Nauru", 'name_ar' => "ناورو", 'phonecode' => 674),
		array('id' => 153,'code' => 'NP','name_en' => "Nepal", 'name_ar' => "نيبال", 'phonecode' => 977),
		array('id' => 154,'code' => 'AN','name_en' => "Netherlands Antilles", 'name_ar' => "جزر الأنتيل الهولندية", 'phonecode' => 599),
		array('id' => 155,'code' => 'NL','name_en' => "Netherlands The", 'name_ar' => "هولندا", 'phonecode' => 31),
		array('id' => 156,'code' => 'NC','name_en' => "New Caledonia", 'name_ar' => "كاليدونيا الجديدة", 'phonecode' => 687),
		array('id' => 157,'code' => 'NZ','name_en' => "New Zealand", 'name_ar' => "نيوزيلاندا", 'phonecode' => 64),
		array('id' => 158,'code' => 'NI','name_en' => "Nicaragua", 'name_ar' => "نيكاراغوا", 'phonecode' => 505),
		array('id' => 159,'code' => 'NE','name_en' => "Niger", 'name_ar' => "النيجر", 'phonecode' => 227),
		array('id' => 160,'code' => 'NG','name_en' => "Nigeria", 'name_ar' => "نيجيريا", 'phonecode' => 234),
		array('id' => 161,'code' => 'NU','name_en' => "Niue", 'name_ar' => "نيوي", 'phonecode' => 683),
		array('id' => 162,'code' => 'NF','name_en' => "Norfolk Island", 'name_ar' => "جزيرة نورفولك", 'phonecode' => 672),
		array('id' => 163,'code' => 'MP','name_en' => "Northern Mariana Islands", 'name_ar' => "جزر مريانا الشمالية", 'phonecode' => 1670),
		array('id' => 164,'code' => 'NO','name_en' => "Norway", 'name_ar' => "النرويج", 'phonecode' => 47),
		array('id' => 165,'code' => 'OM','name_en' => "Oman", 'name_ar' => "سلطنة عمان", 'phonecode' => 968),
		array('id' => 166,'code' => 'PK','name_en' => "Pakistan", 'name_ar' => "باكستان", 'phonecode' => 92),
		array('id' => 167,'code' => 'PW','name_en' => "Palau", 'name_ar' => "بالاو", 'phonecode' => 680),
		array('id' => 168,'code' => 'PS','name_en' => "Palestinian Territory Occupied", 'name_ar' => "الأراضي الفلسطينية المحتلة", 'phonecode' => 970),
		array('id' => 169,'code' => 'PA','name_en' => "Panama", 'name_ar' => "بنما", 'phonecode' => 507),
		array('id' => 170,'code' => 'PG','name_en' => "Papua new Guinea", 'name_ar' => "بابوا غينيا الجديدة", 'phonecode' => 675),
		array('id' => 171,'code' => 'PY','name_en' => "Paraguay", 'name_ar' => "باراغواي", 'phonecode' => 595),
		array('id' => 172,'code' => 'PE','name_en' => "Peru", 'name_ar' => "بيرو", 'phonecode' => 51),
		array('id' => 173,'code' => 'PH','name_en' => "Philippines", 'name_ar' => "فلبين", 'phonecode' => 63),
		array('id' => 174,'code' => 'PN','name_en' => "Pitcairn Island", 'name_ar' => "جزيرة بيتكيرن", 'phonecode' => 0),
		array('id' => 175,'code' => 'PL','name_en' => "Poland", 'name_ar' => "بولندا", 'phonecode' => 48),
		array('id' => 176,'code' => 'PT','name_en' => "Portugal", 'name_ar' => "البرتغال", 'phonecode' => 351),
		array('id' => 177,'code' => 'PR','name_en' => "Puerto Rico", 'name_ar' => "بورتوريكو", 'phonecode' => 1787),
		array('id' => 178,'code' => 'QA','name_en' => "Qatar", 'name_ar' => "قطر", 'phonecode' => 974),
		array('id' => 179,'code' => 'RE','name_en' => "Reunion", 'name_ar' => "ريونيون", 'phonecode' => 262),
		array('id' => 180,'code' => 'RO','name_en' => "Romania", 'name_ar' => "رومانيا", 'phonecode' => 40),
		array('id' => 181,'code' => 'RU','name_en' => "Russia", 'name_ar' => "روسيا", 'phonecode' => 70),
		array('id' => 182,'code' => 'RW','name_en' => "Rwanda", 'name_ar' => "رواندا", 'phonecode' => 250),
		array('id' => 183,'code' => 'SH','name_en' => "Saint Helena", 'name_ar' => "سانت هيلانة", 'phonecode' => 290),
		array('id' => 184,'code' => 'KN','name_en' => "Saint Kitts And Nevis", 'name_ar' => "سانت كيتس ونيفيس", 'phonecode' => 1869),
		array('id' => 185,'code' => 'LC','name_en' => "Saint Lucia", 'name_ar' => "القديسة لوسيا", 'phonecode' => 1758),
		array('id' => 186,'code' => 'PM','name_en' => "Saint Pierre and Miquelon", 'name_ar' => "سانت بيير وميكلون", 'phonecode' => 508),
		array('id' => 187,'code' => 'VC','name_en' => "Saint Vincent And The Grenadines", 'name_ar' => "سانت فنسنت وجزر غرينادين", 'phonecode' => 1784),
		array('id' => 188,'code' => 'WS','name_en' => "Samoa", 'name_ar' => "ساموا", 'phonecode' => 684),
		array('id' => 189,'code' => 'SM','name_en' => "San Marino", 'name_ar' => "سان مارينو", 'phonecode' => 378),
		array('id' => 190,'code' => 'ST','name_en' => "Sao Tome and Principe", 'name_ar' => "ساو تومي وبرينسيبي", 'phonecode' => 239),
		array('id' => 191,'code' => 'SA','name_en' => "Saudi Arabia", 'name_ar' => "المملكة العربية السعودية", 'phonecode' => 966),
		array('id' => 192,'code' => 'SN','name_en' => "Senegal", 'name_ar' => "السنغال", 'phonecode' => 221),
		array('id' => 193,'code' => 'RS','name_en' => "Serbia", 'name_ar' => "صربيا", 'phonecode' => 381),
		array('id' => 194,'code' => 'SC','name_en' => "Seychelles", 'name_ar' => "سيشيل", 'phonecode' => 248),
		array('id' => 195,'code' => 'SL','name_en' => "Sierra Leone", 'name_ar' => "سيرا ليون", 'phonecode' => 232),
		array('id' => 196,'code' => 'SG','name_en' => "Singapore", 'name_ar' => "سنغافورة", 'phonecode' => 65),
		array('id' => 197,'code' => 'SK','name_en' => "Slovakia", 'name_ar' => "سلوفاكيا", 'phonecode' => 421),
		array('id' => 198,'code' => 'SI','name_en' => "Slovenia", 'name_ar' => "سلوفينيا", 'phonecode' => 386),
		array('id' => 199,'code' => 'XG','name_en' => "Smaller Territories of the UK", 'name_ar' => "أقاليم أصغر في المملكة المتحدة", 'phonecode' => 44),
		array('id' => 200,'code' => 'SB','name_en' => "Solomon Islands", 'name_ar' => "جزر سليمان", 'phonecode' => 677),
		array('id' => 201,'code' => 'SO','name_en' => "Somalia", 'name_ar' => "الصومال", 'phonecode' => 252),
		array('id' => 202,'code' => 'ZA','name_en' => "South Africa", 'name_ar' => "أفريقيا الجنوبية", 'phonecode' => 27),
		array('id' => 203,'code' => 'GS','name_en' => "South Georgia", 'name_ar' => "جورجيا الجنوبية", 'phonecode' => 0),
		array('id' => 204,'code' => 'SS','name_en' => "South Sudan", 'name_ar' => "السودان الجنوبية", 'phonecode' => 211),
		array('id' => 205,'code' => 'ES','name_en' => "Spain", 'name_ar' => "إسبانيا", 'phonecode' => 34),
		array('id' => 206,'code' => 'LK','name_en' => "Sri Lanka", 'name_ar' => "سيريلانكا", 'phonecode' => 94),
		array('id' => 207,'code' => 'SD','name_en' => "Sudan", 'name_ar' => "السودان", 'phonecode' => 249),
		array('id' => 208,'code' => 'SR','name_en' => "Suriname", 'name_ar' => "سورينام", 'phonecode' => 597),
		array('id' => 209,'code' => 'SJ','name_en' => "Svalbard And Jan Mayen Islands", 'name_ar' => "جزر سفالبارد وجان ماين", 'phonecode' => 47),
		array('id' => 210,'code' => 'SZ','name_en' => "Swaziland", 'name_ar' => "سوازيلاند", 'phonecode' => 268),
		array('id' => 211,'code' => 'SE','name_en' => "Sweden", 'name_ar' => "السويد", 'phonecode' => 46),
		array('id' => 212,'code' => 'CH','name_en' => "Switzerland", 'name_ar' => "سويسرا", 'phonecode' => 41),
		array('id' => 213,'code' => 'SY','name_en' => "Syria", 'name_ar' => "سوريا", 'phonecode' => 963),
		array('id' => 214,'code' => 'TW','name_en' => "Taiwan", 'name_ar' => "تايوان", 'phonecode' => 886),
		array('id' => 215,'code' => 'TJ','name_en' => "Tajikistan", 'name_ar' => "طاجيكستان", 'phonecode' => 992),
		array('id' => 216,'code' => 'TZ','name_en' => "Tanzania", 'name_ar' => "تنزانيا", 'phonecode' => 255),
		array('id' => 217,'code' => 'TH','name_en' => "Thailand", 'name_ar' => "تايلاند", 'phonecode' => 66),
		array('id' => 218,'code' => 'TG','name_en' => "Togo", 'name_ar' => "توجو", 'phonecode' => 228),
		array('id' => 219,'code' => 'TK','name_en' => "Tokelau", 'name_ar' => "توكيلاو", 'phonecode' => 690),
		array('id' => 220,'code' => 'TO','name_en' => "Tonga", 'name_ar' => "تونغا", 'phonecode' => 676),
		array('id' => 221,'code' => 'TT','name_en' => "Trinidad And Tobago", 'name_ar' => "ترينداد وتوباغو", 'phonecode' => 1868),
		array('id' => 222,'code' => 'TN','name_en' => "Tunisia", 'name_ar' => "تونس", 'phonecode' => 216),
		array('id' => 223,'code' => 'TR','name_en' => "Turkey", 'name_ar' => "تركيا", 'phonecode' => 90),
		array('id' => 224,'code' => 'TM','name_en' => "Turkmenistan", 'name_ar' => "تركمانستان", 'phonecode' => 7370),
		array('id' => 225,'code' => 'TC','name_en' => "Turks And Caicos Islands", 'name_ar' => "جزر تركس وكايكوس", 'phonecode' => 1649),
		array('id' => 226,'code' => 'TV','name_en' => "Tuvalu", 'name_ar' => "توفالو", 'phonecode' => 688),
		array('id' => 227,'code' => 'UG','name_en' => "Uganda", 'name_ar' => "أوغندا", 'phonecode' => 256),
		array('id' => 228,'code' => 'UA','name_en' => "Ukraine", 'name_ar' => "أوكرانيا", 'phonecode' => 380),
		array('id' => 229,'code' => 'AE','name_en' => "United Arab Emirates", 'name_ar' => "الإمارات العربية المتحدة", 'phonecode' => 971),
		array('id' => 230,'code' => 'GB','name_en' => "United Kingdom", 'name_ar' => "المملكة المتحدة", 'phonecode' => 44),
		array('id' => 231,'code' => 'US','name_en' => "United States", 'name_ar' => "الولايات المتحدة الأمريكية", 'phonecode' => 1),
		array('id' => 232,'code' => 'UM','name_en' => "United States Minor Outlying Islands", 'name_ar' => "جزر الولايات المتحدة البعيدة الصغرى", 'phonecode' => 1),
		array('id' => 233,'code' => 'UY','name_en' => "Uruguay", 'name_ar' => "أوروغواي", 'phonecode' => 598),
		array('id' => 234,'code' => 'UZ','name_en' => "Uzbekistan", 'name_ar' => "أوزبكستان", 'phonecode' => 998),
		array('id' => 235,'code' => 'VU','name_en' => "Vanuatu", 'name_ar' => "فانواتو", 'phonecode' => 678),
		array('id' => 236,'code' => 'VA','name_en' => "Vatican City State (Holy See)", 'name_ar' => "الفاتيكان الكرسي الرسولي", 'phonecode' => 39),
		array('id' => 237,'code' => 'VE','name_en' => "Venezuela", 'name_ar' => "فنزويلا", 'phonecode' => 58),
		array('id' => 238,'code' => 'VN','name_en' => "Vietnam", 'name_ar' => "فيتنام", 'phonecode' => 84),
		array('id' => 239,'code' => 'VG','name_en' => "Virgin Islands (British)", 'name_ar' => "جزر العذراء البريطانية", 'phonecode' => 1284),
		array('id' => 240,'code' => 'VI','name_en' => "Virgin Islands (US)", 'name_ar' => "جزر فيرجن الولايات المتحدة", 'phonecode' => 1340),
		array('id' => 241,'code' => 'WF','name_en' => "Wallis And Futuna Islands", 'name_ar' => "جزر واليس وفوتونا", 'phonecode' => 681),
		array('id' => 242,'code' => 'EH','name_en' => "Western Sahara", 'name_ar' => "الصحراء الغربية", 'phonecode' => 212),
		array('id' => 243,'code' => 'YE','name_en' => "Yemen", 'name_ar' => "اليمن", 'phonecode' => 967),
		array('id' => 244,'code' => 'YU','name_en' => "Yugoslavia", 'name_ar' => "يوغوسلافيا", 'phonecode' => 38),
		array('id' => 245,'code' => 'ZM','name_en' => "Zambia", 'name_ar' => "زامبيا", 'phonecode' => 260),
		array('id' => 246,'code' => 'ZW','name_en' => "Zimbabwe", 'name_ar' => "زيمبابوي", 'phonecode' => 263),
		);
		DB::table('countries')->insert($countries);
	}
}
